<?php
/**
 * Created by PhpStorm.
 * User: rauan
 * Date: 3/30/17
 * Time: 4:33 PM
 */

namespace app\components\sections\certificateSection;


use app\components\parents\PageWidget;

class CertificateSection extends PageWidget
{



    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $this->registerClientScript();
        return $this->render('view',['simpleData' => $this->simpleData]);
    }

    protected function registerClientScript()
    {
        $view = $this->getView();
        CertificateSectionAsset::register($view);
    }

}