<?php
/**
 * Created by PhpStorm.
 * User: Rauan
 * Date: 21.06.2016
 * Time: 4:04
 */

namespace app\components\sections\gridSection;


use app\components\parents\PageWidget;
use app\models\Griditem;
use app\models\Page;
use yii\base\UserException;

class GridSection extends PageWidget
{

    public $grids;
    const COLOR = ['1' => 'blue', '2' => 'orange','3' => 'green', '4' => 'grey'];
    const GRID_TYPE = ['default','customUrl','cta'];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(\Yii::getAlias('@device') == 'mobile') {
            $pageUrl = $this->page->url;
            $pageUrl = substr($pageUrl, strlen( \Yii::$app->params['mobilePrefix']));
            $this->page = Page::find()->where(['url' => $pageUrl])->one();
            if (is_null($this->page))
                throw new UserException('You should create page');
        }
        $this->grids = $this->getGrids($this->page);
    }


    public function getGrids($page)
    {
        return Griditem::find()->where(['parent_page_id' => $page->id])->orderBy(['order' => SORT_ASC ])->all();
    }

    private function getGridCategoriesDictionary()
    {
        $dictionary = [];
        foreach ($this->grids as $grid){
            if($grid->page->title == 'CustomPage'){
                if(explode('|',$grid->info)[0] == 'CTA')
                    $dictionary[$grid->id] = self::GRID_TYPE[2];
                else $dictionary[$grid->id] = self::GRID_TYPE[1];
            }
            else $dictionary[$grid->id] = self::GRID_TYPE[0];
        }
        return $dictionary;
    }

    public function run()
    {
        parent::run();
        if(\Yii::getAlias('@device') != 'mobile')
        {
            return $this->render('view',['grids' => $this->grids,'color' => self::COLOR, 'gridDictionary' => $this->getGridCategoriesDictionary()]);

        }
        return $this->render('mobile',['grids' => $this->grids,'color' => self::COLOR, 'gridDictionary' => $this->getGridCategoriesDictionary()]);

    }




}