<?php
/**
 * Created by PhpStorm.
 * User: rauan
 * Date: 3/30/17
 * Time: 12:54 AM
 */

namespace app\components\sections\shortreadSection;


use app\components\parents\PageWidget;

class ShortReadSection extends PageWidget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getRepairedDevice(){
        //TODO : Get API with ginCore
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        return $this->render('view',['simpleData' => $this->simpleData]);
    }


}