<?php
/**
 * Created by PhpStorm.
 * User: rauan
 * Date: 5/16/17
 * Time: 5:09 PM
 */

namespace app\components\sections\mobile\mainSection;


use app\components\parents\PageWidget;

class MainSection extends PageWidget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('view',['simpleData' => $this->simpleData]);
    }

}